import { Customer, Deal, Activity, Contact, Company, ContactHistory } from '@/types';

export const customers: Customer[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john@techcorp.com',
    phone: '(555) 123-4567',
    company: 'TechCorp',
    status: 'active',
    lastContact: '2024-03-20',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah@innovate.co',
    phone: '(555) 987-6543',
    company: 'Innovate Co',
    status: 'active',
    lastContact: '2024-03-18',
  },
];

export const deals: Deal[] = [
  {
    id: '1',
    title: 'Enterprise Software License',
    value: 50000,
    customerId: '1',
    status: 'negotiation',
    expectedCloseDate: '2024-04-15',
    createdAt: '2024-03-01',
    updatedAt: '2024-03-20',
  },
  {
    id: '2',
    title: 'Consulting Services',
    value: 25000,
    customerId: '2',
    status: 'proposal',
    expectedCloseDate: '2024-04-30',
    createdAt: '2024-03-10',
    updatedAt: '2024-03-18',
  },
];

export const activities: Activity[] = [
  {
    id: '1',
    type: 'call',
    title: 'Initial Discussion',
    description: 'Discussed requirements for enterprise solution',
    customerId: '1',
    dealId: '1',
    dueDate: '2024-03-21',
    completed: false,
    createdAt: '2024-03-20',
  },
  {
    id: '2',
    type: 'meeting',
    title: 'Proposal Review',
    description: 'Review consulting proposal with client',
    customerId: '2',
    dealId: '2',
    dueDate: '2024-03-22',
    completed: false,
    createdAt: '2024-03-18',
  },
];

export const contacts: Contact[] = [
  {
    id: '1',
    name: 'Michael Chen',
    email: 'michael.chen@techvision.com',
    phone: '(555) 234-5678',
    companyId: '1',
    position: 'CTO',
    category: 'customer',
    status: 'active',
    lastContact: '2024-03-22',
    createdAt: '2024-01-15',
    updatedAt: '2024-03-22',
    notes: 'Key decision maker for enterprise solutions',
    tags: [],
    groups: [],
  },
  {
    id: '2',
    name: 'Emily Rodriguez',
    email: 'emily.r@innovatech.co',
    phone: '(555) 876-5432',
    companyId: '2',
    position: 'Head of Operations',
    category: 'prospect',
    status: 'active',
    lastContact: '2024-03-21',
    createdAt: '2024-02-01',
    updatedAt: '2024-03-21',
    notes: 'Interested in automation solutions',
    tags: [],
    groups: [],
  },
];

export const companies: Company[] = [
  {
    id: '1',
    name: 'TechVision Inc.',
    industry: 'Software',
    website: 'www.techvision.com',
    address: '123 Innovation Drive, Silicon Valley, CA',
    size: 'enterprise',
    status: 'active',
    createdAt: '2024-01-01',
    updatedAt: '2024-03-22',
  },
  {
    id: '2',
    name: 'InnovaTech Solutions',
    industry: 'IT Services',
    website: 'www.innovatech.co',
    address: '456 Tech Park, Boston, MA',
    size: 'medium',
    status: 'active',
    createdAt: '2024-01-15',
    updatedAt: '2024-03-21',
  },
];

export const contactHistory: ContactHistory[] = [
  {
    id: '1',
    contactId: '1',
    type: 'meeting',
    title: 'Initial Consultation',
    description: 'Discussed enterprise solution requirements and timeline',
    date: '2024-03-22',
    createdAt: '2024-03-22',
  },
  {
    id: '2',
    contactId: '1',
    type: 'email',
    title: 'Follow-up Documentation',
    description: 'Sent detailed proposal and pricing information',
    date: '2024-03-21',
    createdAt: '2024-03-21',
  },
  {
    id: '3',
    contactId: '1',
    type: 'call',
    title: 'Technical Discussion',
    description: 'Reviewed technical specifications and integration requirements',
    date: '2024-03-20',
    createdAt: '2024-03-20',
  },
  {
    id: '4',
    contactId: '1',
    type: 'note',
    title: 'Internal Update',
    description: 'Team aligned on next steps and resource allocation',
    date: '2024-03-19',
    createdAt: '2024-03-19',
  },
  {
    id: '5',
    contactId: '1',
    type: 'meeting',
    title: 'Product Demo',
    description: 'Demonstrated key features and capabilities to stakeholders',
    date: '2024-03-18',
    createdAt: '2024-03-18',
  },
];