apiVersion: apps/v1
kind: Deployment
metadata:
  name: wellnoxcrm
  labels:
    app: wellnoxcrm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wellnoxcrm
  template:
    metadata:
      labels:
        app: wellnoxcrm
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: wellnoxcrm
        image: kpmrafeeq/wellnoxcrm:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: wellnoxcrm-secrets
              key: mongodb-uri
        - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: wellnoxcrm-secrets
              key: stripe-publishable-key 
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: wellnoxcrm-secrets
              key: stripe-secret-key
        - name: STRIPE_PRO_PLAN_PRICE_ID
          valueFrom:
            secretKeyRef:
              name: wellnoxcrm-secrets
              key: stripe-pro-plan-price-id
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: wellnoxcrm-secrets
              key: jwt-secret
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
