kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: innovcrm
  namespace: fleet-default
spec:
  repo: https://github.com/yourusername/innovcrm
  branch: main
  paths:
  - infrastructure
  targets:
  - name: prod
    clusterSelector:
      matchLabels:
        environment: production
    customizations:
      helm:
        values:
          environment: production
          replicas: 3
          domain: crm.innovzone.com
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"

        values:
          environment: staging
          replicas: 1
          domain: staging.innovcrm.example.com
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"