apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: innovcrm-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - innovcrm.example.com
    secretName: innovcrm-tls-secret
  rules:
  - host: innovcrm.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: innovcrm
            port:
              number: 80