apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-crm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn  # Use your cluster's storage class
