apiVersion: v1
kind: Service
metadata:
  name: wellnoxcrm
  labels:
    app: wellnoxcrm
spec:
  selector:
    app: wellnoxcrm
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
